# Generated by Django 5.1.7 on 2025-03-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stitching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_customer",
                to="stitching.studentmeasurement",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="measurement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_measurement",
                to="stitching.studentmeasurement",
            ),
        ),
    ]
