# Generated by Django 5.1.7 on 2025-03-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stitching", "0002_alter_order_customer_alter_order_measurement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.AlterField(
            model_name="order",
            name="fabric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="stitching.fabricaccessory",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="measurement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="stitching.studentmeasurement",
            ),
        ),
    ]
